language: java

install: 
  - sudo apt-get update -q
  - sudo apt-get install -y leptonica

script: "mvn clean install"

jdk:
  - oraclejdk8

notifications:
  email:
    - pipistik.bunciak@gmail.com

branches:
  only:
    - master
