language: java

install: 
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main universe"
  - sudo apt-get update -q
  - sudo apt-get install -y gcc-4.8

script: "mvn clean install"

jdk:
  - oraclejdk8

notifications:
  email:
    - pipistik.bunciak@gmail.com

branches:
  only:
    - master
